---
layout: cv
title: Colin Clough
---
# Colin Clough
Aspirirng Quantitative Software Engineer

<div id="webaddress">
<a href="cloughcolin@gmail.com"></a>



## Currently

Studying at BYU-Idaho pursuing a Bachelors Degree

### Specialized in

Python, C#, Data Cleaning, Problem Solving


### Research interests

Machine Learning, AI, Quanitative Trends

## Education

`2024-2027`
__Brigham Young University Idaho__


<!-- ## Awards -->



<!-- ## Publications -->



## Occupations

## Life Insurance Specialist

`May 2024 - Present`
__CNO Financial Group__, Remote

- Specialize in communications with clients daily and navigate Life Insurance options to ensure financial security
- Improved as a team to reach company goals and beat sales expectations weekly
- Specialized In all lines of life insurance policies including polices ranging from $20k to multimillion dollar policies

## Luxury Valet

`February 2024 - August 2024`
__Elevate Parking__, Scottsdale, AZ

- Ensured safety and efficiency when operating multi-million dollar vehicles
- Handled distribution of cash from thousands of clients and multiple valets
- Led teams of 5 ensuring customer satisfaction and efficient operations

## Valet Manager

`January 2023 - February 2024`
__Integrity Valet__, Phoenix, AZ

- Managed over 100 individual valets ensuring efficiency and smooth operations
- Communicated with 10+ event managers, private clients and owners of restaurants worth 5 million+ dollars
- Maintained contact with each location and help smooth over stressful situations including back ups of hundreds of cars and clients

## Front End Manager

`January 2011 - January 2023`
__Q-up BBQ__, Phoenix, AZ

- Managed Front end operations such as stocking product, making sure services run efficiently, communications with event managers and distribution thousands of dollars to and from clients
- Experienced in customer service such as, handling customer complaints, delivering top notch customer service

## Life Insurance Agent

`August 2023 - May 2024`
__Assurance IQ__, Remote

- Consulted with thousands of clients and selected custom insurance for each client
- Was working with 4 of the largest Life Insurance Carriers in the industry. Solved complex problems of each client and ensured proper coverage for each individual

## Business Consultant

`April 2025`
__Pick PT__, Rexburg, ID

- Conducted In depth Market Research for a Physical Therapy Practice looking to expand its reach to a younger audience specifically college students
- Provided solutions to reach over 4,500 students and between 500-2,000 new students per semester
- Created relationships between 15 different apartment complexes / businesses

<!-- ### Footer

Last updated: May 2013 -->